USE [KIGO]

--First problem
SELECT  cat.CATEGORY_NAME,Count(Item_id) AS N_ITEMS, AVG(Item_Price) AS AVERAGE_PRICE 
FROM dbo.CATEGORIES cat
LEFT JOIN dbo.Items itms ON itms.CATEGORY_ID=cat.CATEGORY_ID
GROUP BY cat.CATEGORY_NAME
ORDER BY 2 DESC,1 ASC


--second problem
SELECT  cat.CATEGORY_NAME
FROM dbo.CATEGORIES cat
LEFT JOIN dbo.Items itms ON itms.CATEGORY_ID=cat.CATEGORY_ID
GROUP BY cat.CATEGORY_NAME
HAVING COUNT(itms.ITEM_ID)<=1



